export default [
    {
        id: 0,
        nome: 'do1',
        som: 'p_c4',
        som_sax: 's_c4',
        som_guitar: 'v_c4',
    },
    {
        id: 1,
        nome: 're1',
        som: 'p_d4',
        som_sax: 's_d4',
        som_guitar: 'v_d4',
    },
    {
        id: 2,
        nome: 'mi1',
        som: 'p_e4',
        som_sax: 's_e4',
        som_guitar: 'v_e4',
    },
    {
        id: 3,
        nome: 'fa1',
        som: 'p_f4',
        som_sax: 's_f4',
        som_guitar: 'v_f4',
    },
    {
        id: 4,
        nome: 'sol1',
        som: 'p_g4',
        som_sax: 's_g4',
        som_guitar: 'v_g4',
    },
    {
        id: 5,
        nome: 'la1',
        som: 'p_a4',
        som_sax: 's_a4',
        som_guitar: 'v_a4',
    },
    {
        id: 6,
        nome: 'si1',
        som: 'p_b4',
        som_sax: 's_b4',
        som_guitar: 'v_b4',
    },
    {
        id: 7,
        nome: 'do2',
        som: 'p_c5',
        som_sax: 's_c5',
        som_guitar: 'v_c5',
    },
    {
        id: 8,
        nome: 're2',
        som: 'p_d5',
        som_sax: 's_d5',
        som_guitar: 'v_d5',
    },
    {
        id: 9,
        nome: 'mi2',
        som: 'p_e5',
        som_sax: 's_e5',
        som_guitar: 'v_e5',
    },
    {
        id: 10,
        nome: 'fa2',
        som: 'p_f5',
        som_sax: 's_f5',
        som_guitar: 'v_f5',
    },
    {
        id: 11,
        nome: 'sol2',
        som: 'p_g5',
        som_sax: 's_g5',
        som_guitar: 'v_g5',
    },    
]